version: 2
registries:
  artifactory:
    type: cargo-registry
    registry: "artifactory"
    url: https://jfrogghdemo.jfrog.io/artifactory/api/cargo/dependabot-cargo/index/
    token: "Token Bearer ${{secrets.CARGO_TOKEN}}"
    
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries: 
      - "artifactory"
    schedule:
      interval: "daily"
    groups:
      artifactory-dependency-group:
        patterns:
          - "*" # Soon, we'll use "delta_*"
